// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP_lX6coMevSA0cTdTsOTL_bAvBoCQgT8',
    appId: '1:841659890707:web:6b7f51f0ebd987b84d93e6',
    messagingSenderId: '841659890707',
    projectId: 'crm-app-89af6',
    authDomain: 'crm-app-89af6.firebaseapp.com',
    storageBucket: 'crm-app-89af6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuH15oKxGQTmmndqXAlJvp3RTqkZZWsAc',
    appId: '1:841659890707:android:6daa86877f35ea5c4d93e6',
    messagingSenderId: '841659890707',
    projectId: 'crm-app-89af6',
    storageBucket: 'crm-app-89af6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiHla3lOz-8gE0WS6t2dpNkzk_k1BUy18',
    appId: '1:841659890707:ios:f5f431f11b4ba2774d93e6',
    messagingSenderId: '841659890707',
    projectId: 'crm-app-89af6',
    storageBucket: 'crm-app-89af6.firebasestorage.app',
    iosBundleId: 'com.example.crmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiHla3lOz-8gE0WS6t2dpNkzk_k1BUy18',
    appId: '1:841659890707:ios:f5f431f11b4ba2774d93e6',
    messagingSenderId: '841659890707',
    projectId: 'crm-app-89af6',
    storageBucket: 'crm-app-89af6.firebasestorage.app',
    iosBundleId: 'com.example.crmApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP_lX6coMevSA0cTdTsOTL_bAvBoCQgT8',
    appId: '1:841659890707:web:c92955b2fdf13fa44d93e6',
    messagingSenderId: '841659890707',
    projectId: 'crm-app-89af6',
    authDomain: 'crm-app-89af6.firebaseapp.com',
    storageBucket: 'crm-app-89af6.firebasestorage.app',
  );
}
